// Copyright 2015 Brendan Zabarauskas and the gl-rs developers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Making sure that no warning is generated by code from generate_gl_bindings!
#![deny(warnings)]
#![allow(
    // Allow clashing definitions because we're pasting and testing all APIs at once (with
    // references to different types).
    clashing_extern_declarations,

    unused_imports,
    clippy::let_and_return,
    clippy::let_unit_value,
    clippy::missing_transmute_annotations,
    clippy::too_many_arguments,
    clippy::unused_unit,
    clippy::upper_case_acronyms,
)]

include!(concat!(env!("OUT_DIR"), "/test_no_warnings.rs"));
